"""create_support_lines_tickets_messages

Revision ID: 8c3a971c267b
Revises: 6e1371d1cfae
Create Date: 2026-09-09 13:58:42.132439

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c3a971c267b"
down_revision: str | Sequence[str] | None = "6e1371d1cfae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support_lines",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("line_id", sa.SmallInteger(), nullable=True),
        sa.Column("assigned_operator_id", sa.Uuid(), nullable=True),
        sa.Column(
            "priority",
            sa.String(length=4),
            server_default="P2",
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("escalation_reason", sa.String(length=64), nullable=True),
        sa.Column("transferred_from_operator_id", sa.Uuid(), nullable=True),
        sa.Column("transfer_comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IN ('P0', 'P1', 'P2')", name="chk_ticket_priority"
        ),
        sa.CheckConstraint(
            "status IN ('bot_processing', 'queued', 'assigned', 'in_progress', 'resolved', 'closed_by_inactivity', 'closed_by_moderation', 'canceled')",
            name="chk_ticket_status",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_operator_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["line_id"], ["support_lines.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["transferred_from_operator_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tickets_chat_history",
        "tickets",
        ["chat_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tickets_chat_id"), "tickets", ["chat_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("sender_type", sa.String(length=16), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "moderation_status",
            sa.String(length=16),
            server_default="passed",
            nullable=False,
        ),
        sa.Column("moderation_reason", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "moderation_status IN ('passed', 'flagged', 'blocked')",
            name="chk_message_moderation_status",
        ),
        sa.CheckConstraint(
            "sender_type IN ('client', 'bot', 'operator', 'system')",
            name="chk_message_sender_type",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["tickets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_messages_ticket_feed",
        "messages",
        ["ticket_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_ticket_id"), "messages", ["ticket_id"], unique=False
    )
    op.create_table(
        "message_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.String(length=64), nullable=False),
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("quote_text", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_message_sources_chunk",
        "message_sources",
        ["chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_message_sources_message_id"),
        "message_sources",
        ["message_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_message_sources_message_id"), table_name="message_sources"
    )
    op.drop_index("idx_message_sources_chunk", table_name="message_sources")
    op.drop_table("message_sources")
    op.drop_index(op.f("ix_messages_ticket_id"), table_name="messages")
    op.drop_index("idx_messages_ticket_feed", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_tickets_chat_id"), table_name="tickets")
    op.drop_index("idx_tickets_chat_history", table_name="tickets")
    op.drop_table("tickets")
    op.drop_table("support_lines")
    # ### end Alembic commands ###
