"""create_kb_tables

Revision ID: e3c0f7088410
Revises: 8c3a971c267b
Create Date: 2026-09-09 15:35:59.209619

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3c0f7088410"
down_revision: str | Sequence[str] | None = "8c3a971c267b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_documents",
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("regime", sa.String(length=32), nullable=True),
        sa.Column(
            "edition_date",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('uploaded', 'indexing', 'indexed', 'failed', 'deprecated')",
            name="chk_document_status",
        ),
        sa.PrimaryKeyConstraint("doc_id"),
    )
    op.create_index(
        "idx_kb_documents_status", "kb_documents", ["status"], unique=False
    )
    op.create_table(
        "kb_nodes",
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("parent_node_id", sa.String(length=64), nullable=True),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("section_path", sa.Text(), nullable=False),
        sa.Column("article_no", sa.String(length=32), nullable=True),
        sa.Column("part_no", sa.String(length=32), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("full_content", sa.Text(), nullable=False),
        sa.Column("table_md", sa.Text(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["doc_id"], ["kb_documents.doc_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_node_id"], ["kb_nodes.node_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("node_id"),
    )
    op.create_index(
        "idx_kb_nodes_lookup",
        "kb_nodes",
        ["doc_id", "article_no", "part_no"],
        unique=False,
    )
    op.create_index(
        "idx_kb_nodes_parent", "kb_nodes", ["parent_node_id"], unique=False
    )
    op.create_index(
        "idx_kb_nodes_path",
        "kb_nodes",
        ["doc_id", "section_path"],
        unique=False,
    )
    op.create_table(
        "kb_article_references",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_node_id", sa.String(length=64), nullable=False),
        sa.Column("to_node_id", sa.String(length=64), nullable=True),
        sa.Column("raw_label", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_node_id"], ["kb_nodes.node_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["to_node_id"], ["kb_nodes.node_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_kb_refs_from",
        "kb_article_references",
        ["from_node_id"],
        unique=False,
    )
    op.create_index(
        "idx_kb_refs_to", "kb_article_references", ["to_node_id"], unique=False
    )
    op.create_table(
        "kb_chunks",
        sa.Column("chunk_id", sa.String(length=64), nullable=False),
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("context_prefix", sa.Text(), nullable=True),
        sa.Column(
            "hyp_questions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "embedding_model_version", sa.String(length=32), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["node_id"], ["kb_nodes.node_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("chunk_id"),
    )
    op.create_index(
        "idx_kb_chunks_node", "kb_chunks", ["node_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_kb_chunks_node", table_name="kb_chunks")
    op.drop_table("kb_chunks")
    op.drop_index("idx_kb_refs_to", table_name="kb_article_references")
    op.drop_index("idx_kb_refs_from", table_name="kb_article_references")
    op.drop_table("kb_article_references")
    op.drop_index("idx_kb_nodes_path", table_name="kb_nodes")
    op.drop_index("idx_kb_nodes_parent", table_name="kb_nodes")
    op.drop_index("idx_kb_nodes_lookup", table_name="kb_nodes")
    op.drop_table("kb_nodes")
    op.drop_index("idx_kb_documents_status", table_name="kb_documents")
    op.drop_table("kb_documents")
    # ### end Alembic commands ###
