"""create_operator_profiles

Revision ID: f078d2afd420
Revises: e3c0f7088410
Create Date: 2026-09-09 20:53:22.314519

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f078d2afd420"
down_revision: str | Sequence[str] | None = "e3c0f7088410"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operator_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("line_id", sa.SmallInteger(), nullable=False),
        sa.Column(
            "shift_status",
            sa.String(length=16),
            server_default="offline",
            nullable=False,
        ),
        sa.Column(
            "max_slots", sa.SmallInteger(), server_default="5", nullable=False
        ),
        sa.Column(
            "disconnected_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "last_assigned_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "shift_status IN ('active', 'break', 'offline')",
            name="chk_operator_shift_status",
        ),
        sa.CheckConstraint(
            "max_slots > 0 AND max_slots <= 20", name="chk_operator_max_slots"
        ),
        sa.ForeignKeyConstraint(
            ["line_id"], ["support_lines.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        "idx_operator_profiles_dispatch",
        "operator_profiles",
        ["line_id", "shift_status"],
        unique=False,
        postgresql_where=sa.text("shift_status = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_operator_profiles_dispatch",
        table_name="operator_profiles",
        postgresql_where=sa.text("shift_status = 'active'"),
    )
    op.drop_table("operator_profiles")
    # ### end Alembic commands ###
